wandb_version: 1

architecture:
  desc: null
  value: UNET
dataset:
  desc: null
  value: MNIST
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719271649
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 83
      2:
      - 1
      - 41
      - 49
      - 55
      - 83
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.17.0
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
